name: CI (rust-carving branch)
permissions:
  contents: read
  statuses: write
  security-events: write
on:
  push:
    branches: [ rust-carving ]
  pull_request:
    branches: [ rust-carving ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install maturin
        run: pip install maturin
      - name: Build and install Rust extension
        run: |
          cd rustcarver
          maturin develop
          cd ..
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          flake8 artefact tests
      - name: Run tests with coverage
        run: |
          pip install pytest-cov
          pytest --cov=artefact --cov-report=xml --cov-report=term
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Security audit with pip-audit
        run: |
          pip install pip-audit
          pip-audit
